# Generated by Django 5.2.18 on 2026-10-09 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('web', 'Navigateur (Web Push)'), ('fcm', "Firebase (Android, et iPhone si l'appli utilise Firebase)"), ('apns', 'Apple direct (iPhone sans Firebase)'), ('expo', 'Expo (appli React Native Expo)')], max_length=8)),
                ('token', models.TextField()),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('p256dh', models.CharField(blank=True, default='', max_length=255)),
                ('auth', models.CharField(blank=True, default='', max_length=255)),
                ('apns_sandbox', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'kind'], name='push_notifi_user_id_5b255c_idx')],
            },
        ),
    ]
