"""Tests for the invite/accept/revoke flow."""
from __future__ import annotations

from datetime import timedelta

import pytest
from django.utils import timezone

from team_membership_invites.models import TeamInvite, TeamMember
from team_membership_invites.selectors import (
    pending_invites_for_email,
    pending_invites_for_team,
)
from team_membership_invites.services import (
    TeamServiceError,
    accept_invite,
    invite,
    revoke_invite,
)


@pytest.mark.django_db
def test_invite_creates_pending_row(team, creator, other_user):
    inv = invite(team=team, email=other_user.email, invited_by=creator)
    assert inv.pk is not None
    assert inv.email == other_user.email.lower()
    assert inv.token  # generated by default
    assert inv.expires_at > timezone.now()
    assert inv.accepted_at is None


@pytest.mark.django_db
def test_invite_dedups_pending_row(team, creator):
    inv1 = invite(team=team, email="new@example.com", invited_by=creator)
    inv2 = invite(team=team, email="new@example.com", invited_by=creator)
    assert inv1.pk == inv2.pk
    assert TeamInvite.objects.filter(team=team).count() == 1


@pytest.mark.django_db
def test_invite_normalizes_email_case(team, creator):
    inv = invite(team=team, email="MixEd@EXAMPLE.com", invited_by=creator)
    assert inv.email == "mixed@example.com"


@pytest.mark.django_db
def test_invite_existing_member_rejected(team, creator, other_user):
    # Make other_user a member first
    invite_obj = invite(team=team, email=other_user.email, invited_by=creator)
    accept_invite(token=invite_obj.token, user=other_user)
    # Now reinviting should fail
    with pytest.raises(TeamServiceError):
        invite(team=team, email=other_user.email, invited_by=creator)


@pytest.mark.django_db
def test_accept_invite_inserts_member_and_marks_accepted(team, creator, other_user):
    inv = invite(team=team, email=other_user.email, invited_by=creator)
    member = accept_invite(token=inv.token, user=other_user)
    assert member.team_id == team.pk
    assert member.user_id == other_user.id
    inv.refresh_from_db()
    assert inv.accepted_at is not None


@pytest.mark.django_db
def test_double_accept_rejected(team, creator, other_user):
    inv = invite(team=team, email=other_user.email, invited_by=creator)
    accept_invite(token=inv.token, user=other_user)
    with pytest.raises(TeamServiceError, match="already accepted"):
        accept_invite(token=inv.token, user=other_user)


@pytest.mark.django_db
def test_accept_email_mismatch_rejected(team, creator, other_user, third_user):
    inv = invite(team=team, email=other_user.email, invited_by=creator)
    with pytest.raises(TeamServiceError, match="different email"):
        accept_invite(token=inv.token, user=third_user)


@pytest.mark.django_db
def test_accept_expired_rejected(team, creator, other_user):
    inv = invite(team=team, email=other_user.email, invited_by=creator)
    inv.expires_at = timezone.now() - timedelta(days=1)
    inv.save(update_fields=["expires_at"])
    with pytest.raises(TeamServiceError, match="expired"):
        accept_invite(token=inv.token, user=other_user)


@pytest.mark.django_db
def test_revoke_invite_then_accept_rejected(team, creator, other_user):
    inv = invite(team=team, email=other_user.email, invited_by=creator)
    revoke_invite(token=inv.token, by=creator)
    with pytest.raises(TeamServiceError, match="revoked"):
        accept_invite(token=inv.token, user=other_user)


@pytest.mark.django_db
def test_accept_unknown_token_rejected(other_user):
    with pytest.raises(TeamServiceError, match="not found"):
        accept_invite(token="bogus-token-xxx", user=other_user)


@pytest.mark.django_db
def test_pending_invites_for_team_excludes_accepted(team, creator, other_user, third_user):
    inv_other = invite(team=team, email=other_user.email, invited_by=creator)
    invite(team=team, email=third_user.email, invited_by=creator)
    # Accept one
    accept_invite(token=inv_other.token, user=other_user)
    pending = list(pending_invites_for_team(team))
    assert len(pending) == 1
    assert pending[0].email == third_user.email


@pytest.mark.django_db
def test_pending_invites_for_email_returns_outstanding(team, creator, other_user):
    invite(team=team, email=other_user.email, invited_by=creator)
    pending = list(pending_invites_for_email(other_user.email))
    assert len(pending) == 1
    assert pending[0].team_id == team.pk
